# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0003_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='post date'),
        ),
    ]
